### ISSUE TITLE
Exception after upgrade of log4j2 to 2.8.2  

### ISSUE THREAD

**Issue by MarinaRazumovsky** [logzio/logzio-log4j2-appender#8]
Root Cause: class java.lang.NoSuchMethodError
-- org.apache.logging.log4j.core.impl.ThrowableProxy.getCauseStackTraceAsString()Ljava/lang/String;
io.logz.log4j2.LogzioAppender.formatMessageAsJson(LogzioAppender.java:335)
io.logz.log4j2.LogzioAppender.append(LogzioAppender.java:309)
org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)

**Comment by MarinaRazumovsky** [comment]
Closed version 1.5
